name: ndcube

channels:
    - conda-forge

dependencies:
    - python=3
    - astropy
    - Cython
    - matplotlib
    - numpy
    - openjpeg 
    - jinja2
    - scipy
    - requests
    - beautifulsoup4
    - sqlalchemy
    - scikit-image
    - pandas
    - nomkl
    - glymur
    - suds-jurko
    - pip:
      - sunpy==0.8.rc1
      - sunpy-sphinx-theme
